AllCops:
  # Exclude anything that isn't really part of our code.
  # rails_helper is excluded because it's full of solecisms, but it's mostly
  # generated code and copy-and-pasted snipets from READMEs.
  Exclude:
    - 'app/controllers/api/v1/schemas/*'
    - 'app/models/schemas/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'vendor/**/*'

# Prefer sensible naming to comments everywhere.
Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Metrics/AbcSize:
  Max: 17

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 120

CyclomaticComplexity:
  Max: 7

# No-one in this team uses a fixed-width terminal
Metrics/LineLength:
  Max: 120

Style/FrozenStringLiteralComment:
  Enabled: false
