default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: <%= ENV['OFFENDERS_API_DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['OFFENDERS_API_DATABASE_USERNAME'] %>
  password: <%= ENV['OFFENDERS_API_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: offenders_api_development

test: &test
  <<: *default
  database: 'offenders_api_test'

production:
  <<: *default
  database: <%= ENV['OFFENDERS_API_DATABASE'] %>

cucumber:
  <<: *test
