default: &default
  adapter: sqlserver
  # mode: dblib
  host: <%= ENV['OFFENDERS_API_DATABASE_HOST'] || 'localhost' %>
  port: 1433
  username: <%= ENV['OFFENDERS_API_DATABASE_USERNAME'] %>
  password: <%= ENV['OFFENDERS_API_DATABASE_PASSWORD'] %>
  timeout: 5000
  azure: true

development:
  <<: *default
  database: <%= ENV['OFFENDERS_API_DATABASE'] %>_development

test: &test
  <<: *default
  database: <%= ENV['OFFENDERS_API_DATABASE'] %>_test

production:
  <<: *default
  database: <%= ENV['OFFENDERS_API_DATABASE'] %>_production

cucumber:
  <<: *test
