default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  host: <%= ENV['PRISONERS_API_DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['PRISONERS_API_DATABASE_USERNAME'] %>
  password: <%= ENV['PRISONERS_API_DATABASE_PASSWORD'] %>

development:
  <<: *default
  database: prisoners_api_development

test: &test
  <<: *default
  database: 'prisonsers_api_test'

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  database: prisoners_api
  username: prisoners_api
  password: <%= ENV['PRISONERS_API_DATABASE_PASSWORD'] %>
